# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jeff_table_v1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 110, 561, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_T8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T8.setObjectName("label_T8")
        self.gridLayout.addWidget(self.label_T8, 9, 0, 1, 1)
        self.label_D3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D3.setObjectName("label_D3")
        self.gridLayout.addWidget(self.label_D3, 0, 4, 1, 1)
        self.label_00 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_00.setObjectName("label_00")
        self.gridLayout.addWidget(self.label_00, 1, 1, 1, 1)
        self.label_AA = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_AA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_AA.setObjectName("label_AA")
        self.gridLayout.addWidget(self.label_AA, 0, 0, 1, 1)
        self.label_D4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D4.setObjectName("label_D4")
        self.gridLayout.addWidget(self.label_D4, 0, 5, 1, 1)
        self.label_01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 1, 2, 1, 1)
        self.label_D0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D0.setObjectName("label_D0")
        self.gridLayout.addWidget(self.label_D0, 0, 1, 1, 1)
        self.label_T2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T2.setObjectName("label_T2")
        self.gridLayout.addWidget(self.label_T2, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_T7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T7.setObjectName("label_T7")
        self.gridLayout.addWidget(self.label_T7, 8, 0, 1, 1)
        self.label_D1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D1.setObjectName("label_D1")
        self.gridLayout.addWidget(self.label_D1, 0, 2, 1, 1)
        self.label_D2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_D2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D2.setObjectName("label_D2")
        self.gridLayout.addWidget(self.label_D2, 0, 3, 1, 1)
        self.label_T3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T3.setObjectName("label_T3")
        self.gridLayout.addWidget(self.label_T3, 4, 0, 1, 1)
        self.label_T5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T5.setObjectName("label_T5")
        self.gridLayout.addWidget(self.label_T5, 6, 0, 1, 1)
        self.label_T6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T6.setObjectName("label_T6")
        self.gridLayout.addWidget(self.label_T6, 7, 0, 1, 1)
        self.label_T1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T1.setObjectName("label_T1")
        self.gridLayout.addWidget(self.label_T1, 2, 0, 1, 1)
        self.label_T0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T0.setObjectName("label_T0")
        self.gridLayout.addWidget(self.label_T0, 1, 0, 1, 1)
        self.label_T4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T4.setObjectName("label_T4")
        self.gridLayout.addWidget(self.label_T4, 5, 0, 1, 1)
        self.label_T9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_T9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T9.setObjectName("label_T9")
        self.gridLayout.addWidget(self.label_T9, 10, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 1, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_T8.setText(_translate("Form", "16:30-17:30"))
        self.label_D3.setText(_translate("Form", "Thursday"))
        self.label_00.setText(_translate("Form", "TextLabel"))
        self.label_AA.setText(_translate("Form", "<html><head/><body><p align=\"center\">Time\\Weekday</p></body></html>"))
        self.label_D4.setText(_translate("Form", "Friday"))
        self.label_01.setText(_translate("Form", "TextLabel"))
        self.label_D0.setText(_translate("Form", "Monday"))
        self.label_T2.setText(_translate("Form", "10:30-11:30"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_T7.setText(_translate("Form", "15:30-16:30"))
        self.label_D1.setText(_translate("Form", "Tuesday"))
        self.label_D2.setText(_translate("Form", "Wednesday"))
        self.label_T3.setText(_translate("Form", "11:30-12:30"))
        self.label_T5.setText(_translate("Form", "13:30-14:30"))
        self.label_T6.setText(_translate("Form", "14:30-15:30"))
        self.label_T1.setText(_translate("Form", "09:30-10:30"))
        self.label_T0.setText(_translate("Form", "08:30-09:30"))
        self.label_T4.setText(_translate("Form", "12:30-13:30"))
        self.label_T9.setText(_translate("Form", "17:30-18:30"))
        self.label_20.setText(_translate("Form", "TextLabel"))

