# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'latestPopUpUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PopUp(object):
    def setupUi(self, PopUp):
        PopUp.setObjectName("PopUp")
        PopUp.resize(759, 657)
        self.remind_msg = QtWidgets.QLabel(PopUp)
        self.remind_msg.setGeometry(QtCore.QRect(90, 60, 400, 32))
        self.remind_msg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.remind_msg.setObjectName("remind_msg")
        self.course_id_label = QtWidgets.QLabel(PopUp)
        self.course_id_label.setGeometry(QtCore.QRect(90, 100, 71, 16))
        self.course_id_label.setObjectName("course_id_label")
        self.class_id_label = QtWidgets.QLabel(PopUp)
        self.class_id_label.setGeometry(QtCore.QRect(90, 130, 71, 16))
        self.class_id_label.setObjectName("class_id_label")
        self.date_label = QtWidgets.QLabel(PopUp)
        self.date_label.setGeometry(QtCore.QRect(90, 160, 71, 16))
        self.date_label.setObjectName("date_label")
        self.start_time_label = QtWidgets.QLabel(PopUp)
        self.start_time_label.setGeometry(QtCore.QRect(90, 190, 71, 16))
        self.start_time_label.setObjectName("start_time_label")
        #self.end_time_label = QtWidgets.QLabel(PopUp)
        #self.end_time_label.setGeometry(QtCore.QRect(90, 220, 71, 16))
        #self.end_time_label.setObjectName("end_time_label")
        self.room_label = QtWidgets.QLabel(PopUp)
        self.room_label.setGeometry(QtCore.QRect(90, 250, 71, 16))
        self.room_label.setObjectName("room_label")
        self.zoom_link_label = QtWidgets.QLabel(PopUp)
        self.zoom_link_label.setGeometry(QtCore.QRect(90, 280, 71, 16))
        self.zoom_link_label.setTextFormat(QtCore.Qt.AutoText)
        self.zoom_link_label.setObjectName("zoom_link_label")
        self.news_label = QtWidgets.QLabel(PopUp)
        self.news_label.setGeometry(QtCore.QRect(90, 310, 131, 16))
        self.news_label.setOpenExternalLinks(True)
        self.news_label.setObjectName("news_label")
        self.note_link_label = QtWidgets.QLabel(PopUp)
        self.note_link_label.setGeometry(QtCore.QRect(90, 410, 71, 16))
        self.note_link_label.setTextFormat(QtCore.Qt.AutoText)
        self.note_link_label.setObjectName("note_link_label")
        self.class_teacher_label = QtWidgets.QLabel(PopUp)
        self.class_teacher_label.setGeometry(QtCore.QRect(90, 500, 91, 16))
        self.class_teacher_label.setObjectName("class_teacher_label")
        self.email_and_exit_button = QtWidgets.QPushButton(PopUp)
        self.email_and_exit_button.setGeometry(QtCore.QRect(170, 600, 161, 28))
        self.email_and_exit_button.setObjectName("email_and_exit_button")
        self.exit_button = QtWidgets.QPushButton(PopUp)
        self.exit_button.setGeometry(QtCore.QRect(440, 600, 93, 28))
        self.exit_button.setObjectName("exit_button")
        self.course_id = QtWidgets.QLabel(PopUp)
        self.course_id.setGeometry(QtCore.QRect(160, 100, 121, 16))
        self.course_id.setObjectName("course_id")
        self.class_id = QtWidgets.QLabel(PopUp)
        self.class_id.setGeometry(QtCore.QRect(160, 130, 61, 16))
        self.class_id.setObjectName("class_id")
        self.date = QtWidgets.QLabel(PopUp)
        self.date.setGeometry(QtCore.QRect(160, 160, 55, 16))
        self.date.setObjectName("date")
        self.start_time = QtWidgets.QLabel(PopUp)
        self.start_time.setGeometry(QtCore.QRect(160, 190, 81, 16))
        self.start_time.setObjectName("start_time")
        #self.end_time = QtWidgets.QLabel(PopUp)
        #self.end_time.setGeometry(QtCore.QRect(160, 220, 81, 16))
        #self.end_time.setObjectName("end_time")
        self.room = QtWidgets.QLabel(PopUp)
        self.room.setGeometry(QtCore.QRect(160, 250, 81, 16))
        self.room.setObjectName("room")
        self.zoom_link = QtWidgets.QLabel(PopUp)
        self.zoom_link.setGeometry(QtCore.QRect(160, 280, 561, 16))
        self.zoom_link.setTextFormat(QtCore.Qt.RichText)
        self.zoom_link.setOpenExternalLinks(True)
        self.zoom_link.setObjectName("zoom_link")
        self.news = QtWidgets.QLabel(PopUp)
        self.news.setGeometry(QtCore.QRect(90, 330, 631, 71))
        self.news.setTextFormat(QtCore.Qt.AutoText)
        self.news.setObjectName("news")
        self.note_link = QtWidgets.QLabel(PopUp)
        self.note_link.setGeometry(QtCore.QRect(90, 430, 631, 61))
        self.note_link.setTextFormat(QtCore.Qt.RichText)
        self.note_link.setOpenExternalLinks(True)
        self.note_link.setObjectName("note_link")
        self.class_teacher = QtWidgets.QLabel(PopUp)
        self.class_teacher.setGeometry(QtCore.QRect(180, 500, 321, 16))
        self.class_teacher.setTextFormat(QtCore.Qt.AutoText)
        self.class_teacher.setObjectName("class_teacher")

        self.retranslateUi(PopUp)
        QtCore.QMetaObject.connectSlotsByName(PopUp)

    def retranslateUi(self, PopUp):
        _translate = QtCore.QCoreApplication.translate
        PopUp.setWindowTitle(_translate("PopUp", "Reminder"))
        self.remind_msg.setText(_translate("PopUp", "REMIND MSG"))
        self.course_id_label.setText(_translate("PopUp", "Course ID:"))
        self.class_id_label.setText(_translate("PopUp", "Class ID:"))
        self.date_label.setText(_translate("PopUp", "Date:"))
        self.start_time_label.setText(_translate("PopUp", "Start time:"))
        #self.end_time_label.setText(_translate("PopUp", "End time:"))
        self.room_label.setText(_translate("PopUp", "Room:"))
        self.zoom_link_label.setText(_translate("PopUp", "Zoom link:"))
        self.news_label.setText(_translate("PopUp", "News announcement:"))
        self.note_link_label.setText(_translate("PopUp", "Note link:"))
        self.class_teacher_label.setText(_translate("PopUp", "Class teacher:"))
        self.email_and_exit_button.setText(_translate("PopUp", "Send email and Exit"))
        self.exit_button.setText(_translate("PopUp", "Exit"))
        self.course_id.setText(_translate("PopUp", "COURSE_ID"))
        self.class_id.setText(_translate("PopUp", "CLASS_ID"))
        self.date.setText(_translate("PopUp", "DATE"))
        self.start_time.setText(_translate("PopUp", "START_TIME"))
        #self.end_time.setText(_translate("PopUp", "END_TIME"))
        self.room.setText(_translate("PopUp", "ROOM"))
        self.zoom_link.setText(_translate("PopUp", "CLICK_HERE_TO_GO_ZOOM"))
        self.news.setText(_translate("PopUp", "NEWS"))
        self.note_link.setText(_translate("dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">Github</span></a></p></body></html>"))

        self.class_teacher.setText(_translate("PopUp", "CLASS_TEACHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopUp = QtWidgets.QDialog()
    ui = Ui_PopUp()
    ui.setupUi(PopUp)
    PopUp.show()
    sys.exit(app.exec_())

